# Generated by Django 4.1.3 on 2022-11-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('crew', 'role')},
        ),
    ]
