# Generated by Django 4.1.3 on 2022-11-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviecrew_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'crew', 'role')},
        ),
    ]
