# Generated by Django 4.1.3 on 2022-11-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_crewcomment_options_alter_moviecomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewcomment',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='moviecomment',
            options={'ordering': ['created_time']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='is_valid',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='crewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_%(class)ss', to='movies.crewcomment'),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_%(class)ss', to='movies.moviecomment'),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_movie', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_role', to='movies.role'),
        ),
    ]
