# Generated by Django 4.1.3 on 2022-11-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviecrew_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(10)),
        ),
        migrations.AddField(
            model_name='movie',
            name='voter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
