# Generated by Django 4.1.3 on 2022-11-15 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_rate_movie_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(default=0, verbose_name=django.core.validators.MaxValueValidator(10)),
        ),
    ]
