# Generated by Django 4.1.3 on 2022-11-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_crewcomment_options_alter_moviecomment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='status',
            new_name='is_valid',
        ),
    ]
