# Generated by Django 4.1.3 on 2022-11-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
