# Generated by Django 4.1.3 on 2022-11-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_genre_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='lol',
        ),
    ]
