# Generated by Django 4.1.3 on 2022-11-15 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.TextField(blank=True, verbose_name=django.core.validators.MinValueValidator(10)),
        ),
    ]
