# Generated by Django 4.1.3 on 2022-11-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_comment_created_time_comment_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
