# Generated by Django 4.1.3 on 2022-11-15 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name=django.core.validators.MinValueValidator(3)),
        ),
    ]
